In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

In [218]:
dataset = pd.read_csv('./data/players.csv')

all_traded_players = set()
for row in dataset.index:
    #print(dataset["Tm"][row])
    if dataset["Tm"][row] == "TOT":
        all_traded_players.add(dataset['Player'][row])
        
#print(all_traded_players)

for index,row in dataset.iterrows():
    if row['Player'] in all_traded_players and row['Tm'] != 'TOT':
        #print("hello")
        dataset.drop(index, inplace=True)
    if row["Player"] == "Dwyane Wade":
        dataset.drop(index, inplace=True)
    if row["Player"] == "Dirk Nowitzki":
        dataset.drop(index, inplace=True)


In [228]:
dataset

Player    FG   FGA    FG%   3P  3PA    3P%   2P   2PA  \
0              Alex Abrines   1.8   5.1  0.357  1.3  4.1  0.323  0.5   1.0   
1                Quincy Acy   0.4   1.8  0.222  0.2  1.5  0.133  0.2   0.3   
2              Jaylen Adams   1.1   3.2  0.345  0.7  2.2  0.338  0.4   1.1   
3              Steven Adams   6.0  10.1  0.595  0.0  0.0  0.000  6.0  10.1   
4               Bam Adebayo   3.4   5.9  0.576  0.0  0.2  0.200  3.4   5.7   
5                 Deng Adel   0.6   1.9  0.306  0.3  1.2  0.261  0.3   0.7   
6    DeVaughn Akoon-Purcell   0.4   1.4  0.300  0.0  0.6  0.000  0.4   0.9   
7         LaMarcus Aldridge   8.4  16.3  0.519  0.1  0.5  0.238  8.3  15.8   
8              Rawle Alkins   1.3   3.9  0.333  0.3  1.2  0.250  1.0   2.7   
9             Grayson Allen   1.8   4.7  0.376  0.8  2.6  0.323  0.9   2.1   
10            Jarrett Allen   4.2   7.1  0.590  0.1  0.6  0.133  4.1   6.5   
11             Kadeem Allen   3.4   7.4  0.461  0.9  1.9  0.472  2.5   5.5   
12          Al-Farouq Aminu   3.2   7.3  0.433  1.2  3.5  0.343  2.0   3.9   
13          Justin Anderson   1.3   3.3  0.408  0.5  1.6  0.312  0.8   1.7   
14            Kyle Anderson   3.5   6.4  0.543  0.2  0.8  0.265  3.3   5.6   
15            Ryan Anderson   0.8   2.8  0.304  0.4  1.6  0.225  0.5   1.2   
19    Giannis Antetokounmpo  10.0  17.3  0.578  0.7  2.8  0.256  9.3  14.5   
21          Carmelo Anthony   4.9  12.1  0.405  2.1  6.4  0.328  2.8   5.7   
22               OG Anunoby   2.7   6.0  0.453  1.0  3.0  0.332  1.7   3.0   
23         Ryan Arcidiacono   2.3   5.2  0.447  1.0  2.7  0.373  1.3   2.5   
24             Trevor Ariza   4.3  10.7  0.399  2.1  6.3  0.334  2.2   4.4   
27            D.J. Augustin   3.9   8.4  0.470  1.6  3.8  0.421  2.3   4.5   
28            Deandre Ayton   7.2  12.3  0.585  0.0  0.1  0.000  7.2  12.2   
29             Dwayne Bacon   2.8   6.0  0.475  0.9  2.0  0.437  2.0   4.0   
30        Marvin Bagley III   5.7  11.4  0.504  0.5  1.5  0.313  5.3   9.8   
31                Ron Baker   0.3   1.3  0.200  0.1  0.9  0.077  0.2   0.5   
34             Wade Baldwin   0.6   2.1  0.303  0.1  0.6  0.222  0.5   1.5   
35               Lonzo Ball   3.9   9.7  0.406  1.6  4.9  0.329  2.3   4.9   
36                 Mo Bamba   2.5   5.2  0.481  0.4  1.5  0.300  2.0   3.7   
37               J.J. Barea   4.2  10.1  0.418  1.0  3.4  0.297  3.2   6.8   
..                      ...   ...   ...    ...  ...  ...    ...  ...   ...   
665            Kemba Walker   8.9  20.5  0.434  3.2  8.9  0.356  5.7  11.6   
666           Lonnie Walker   0.9   2.7  0.348  0.3  0.8  0.385  0.6   1.9   
667               John Wall   7.7  17.3  0.444  1.6  5.3  0.302  6.1  12.0   
668          Tyrone Wallace   1.5   3.5  0.424  0.1  0.3  0.211  1.4   3.2   
669          Taurean Prince   4.8  10.8  0.441  2.2  5.7  0.390  2.5   5.1   
670          Brad Wanamaker   1.4   2.9  0.476  0.4  1.1  0.410  0.9   1.8   
671             T.J. Warren   6.9  14.2  0.486  1.8  4.2  0.428  5.1  10.0   
672         Julian Washburn   0.9   2.7  0.333  0.3  1.3  0.208  0.6   1.3   
673           Yuta Watanabe   1.0   3.4  0.294  0.1  1.1  0.125  0.9   2.3   
674            Thomas Welsh   0.6   1.2  0.538  0.3  0.6  0.429  0.4   0.5   
675       Russell Westbrook   8.6  20.2  0.428  1.6  5.6  0.290  7.0  14.5   
676           Derrick White   3.9   8.1  0.479  0.7  2.1  0.338  3.2   6.0   
678        Hassan Whiteside   5.4   9.4  0.571  0.0  0.2  0.125  5.4   9.2   
679          Andrew Wiggins   6.8  16.6  0.412  1.6  4.8  0.339  5.2  11.8   
680           Alan Williams   1.6   2.6  0.615  0.0  0.2  0.000  1.6   2.4   
681           C.J. Williams   1.1   2.3  0.486  0.3  1.1  0.313  0.8   1.3   
682      Johnathan Williams   2.7   4.6  0.591  0.0  0.1  0.000  2.7   4.5   
683        Kenrich Williams   2.3   6.1  0.384  1.1  3.4  0.333  1.2   2.7   
684            Lou Williams   6.5  15.2  0.425  1.4  3.9  0.361  5.1  11.3   
685         Marvin Williams   3.7   8.7  0.

In [229]:
datf[['C', 'D', 'E']]  

NameError: name 'datf' is not defined

In [230]:
dataset = dataset.drop('Id', axis=1)
dataset = dataset.drop('Unnamed: 0', axis=1)
dataset = dataset.drop('Pos', axis=1)
dataset = dataset.drop('Tm', axis=1)
dataset = dataset.drop('G', axis=1)
dataset = dataset.drop('first', axis=1)
dataset = dataset.drop('last', axis=1)
dataset = dataset.drop('Age', axis=1)
dataset = dataset.drop('PF', axis=1)
dataset = dataset.drop('TOV', axis=1)
dataset = dataset.drop('GS', axis=1)
dataset = dataset.drop('MP', axis=1)
dataset = dataset.dropna()

ValueError: labels ['Id'] not contained in axis

In [231]:
dataset.head(5)

Player   FG   FGA    FG%   3P  3PA    3P%   2P   2PA    2P%   ...     \
0  Alex Abrines  1.8   5.1  0.357  1.3  4.1  0.323  0.5   1.0  0.500   ...      
1    Quincy Acy  0.4   1.8  0.222  0.2  1.5  0.133  0.2   0.3  0.667   ...      
2  Jaylen Adams  1.1   3.2  0.345  0.7  2.2  0.338  0.4   1.1  0.361   ...      
3  Steven Adams  6.0  10.1  0.595  0.0  0.0  0.000  6.0  10.1  0.596   ...      
4   Bam Adebayo  3.4   5.9  0.576  0.0  0.2  0.200  3.4   5.7  0.588   ...      

   FTA    FT%  ORB  DRB  TRB  AST  STL  BLK   PTS  allstar  
0  0.4  0.923  0.2  1.4  1.5  0.6  0.5  0.2   5.3        0  
1  1.0  0.700  0.3  2.2  2.5  0.8  0.1  0.4   1.7        0  
2  0.3  0.778  0.3  1.4  1.8  1.9  0.4  0.1   3.2        0  
3  3.7  0.500  4.9  4.6  9.5  1.6  1.5  1.0  13.9        0  
4  2.8  0.735  2.0  5.3  7.3  2.2  0.9  0.8   8.9        0  

[5 rows x 22 columns]

In [240]:
X = dataset.iloc[:,:-1]
X = X.drop('Player', axis=1).values

In [241]:
X

array([[ 1.8  ,  5.1  ,  0.357, ...,  0.5  ,  0.2  ,  5.3  ],
       [ 0.4  ,  1.8  ,  0.222, ...,  0.1  ,  0.4  ,  1.7  ],
       [ 1.1  ,  3.2  ,  0.345, ...,  0.4  ,  0.1  ,  3.2  ],
       ...,
       [ 6.5  , 15.5  ,  0.418, ...,  0.9  ,  0.2  , 19.1  ],
       [ 3.9  ,  7.   ,  0.551, ...,  0.8  ,  0.8  , 10.1  ],
       [ 2.7  ,  5.   ,  0.533, ...,  0.2  ,  0.5  ,  7.7  ]])

In [247]:
Y = dataset[['Player', 'allstar']]

In [248]:
Y

Player  allstar
0              Alex Abrines        0
1                Quincy Acy        0
2              Jaylen Adams        0
3              Steven Adams        0
4               Bam Adebayo        0
5                 Deng Adel        0
6    DeVaughn Akoon-Purcell        0
7         LaMarcus Aldridge        1
8              Rawle Alkins        0
9             Grayson Allen        0
10            Jarrett Allen        0
11             Kadeem Allen        0
12          Al-Farouq Aminu        0
13          Justin Anderson        0
14            Kyle Anderson        0
15            Ryan Anderson        0
19    Giannis Antetokounmpo        1
21          Carmelo Anthony        0
22               OG Anunoby        0
23         Ryan Arcidiacono        0
24             Trevor Ariza        0
27            D.J. Augustin        0
28            Deandre Ayton        0
29             Dwayne Bacon        0
30        Marvin Bagley III        0
31                Ron Baker        0
34             Wade Baldwin        0
35               Lonzo Ball        0
36                 Mo Bamba        0
37               J.J. Barea        0
..                      ...      ...
665            Kemba Walker        1
666           Lonnie Walker        0
667               John Wall        0
668          Tyrone Wallace        0
669          Taurean Prince        0
670          Brad Wanamaker        0
671             T.J. Warren        0
672         Julian Washburn        0
673           Yuta Watanabe        0
674            Thomas Welsh        0
675       Russell Westbrook        1
676           Derrick White        0
678        Hassan Whiteside        0
679          Andrew Wiggins        0
680           Alan Williams        0
681           C.J. Williams        0
682      Johnathan Williams        0
683        Kenrich Williams        0
684            Lou Williams        0
685         Marvin Williams        0
687           Troy Williams        0
688             D.J. Wilson        0
689         Justise Winslow        0
690          Christian Wood        0
693            Delon Wright        0
696      Guerschon Yabusele        0
698          Thaddeus Young        0
699              Trae Young        0
700             Cody Zeller        0
701            Tyler Zeller        0

[473 rows x 2 columns]

In [249]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size = 0.2, random_state=24)

In [250]:
Y_test

Player  allstar
410              Kevin Love        0
215       Cristiano Felício        0
288           Mario Hezonja        0
639            Daniel Theis        0
650             P.J. Tucker        0
124         Tyler Cavanaugh        0
182            Tyler Dorsey        0
5                 Deng Adel        0
619          Omari Spellman        0
390               T.J. Leaf        0
293             George Hill        0
178            Gorgui Dieng        0
145              Quinn Cook        0
147        Robert Covington        0
480           Jaylen Morris        0
701            Tyler Zeller        0
519              Cedi Osman        0
457         Khris Middleton        1
689         Justise Winslow        0
491            Mike Muscala        0
462          Malcolm Miller        0
283           Udonis Haslem        0
6    DeVaughn Akoon-Purcell        0
616            Ray Spalding        0
660             Noah Vonleh        0
3              Steven Adams        0
516             Josh Okogie        0
42         Keita Bates-Diop        0
324       Demetrius Jackson        0
665            Kemba Walker        1
..                      ...      ...
671             T.J. Warren        0
445             CJ McCollum        0
227         Jimmer Fredette        0
86            Lorenzo Brown        0
317          Ersan İlyasova        0
368            Luke Kennard        0
205             Jacob Evans        0
512            Kyle O'Quinn        0
453             Jodie Meeks        0
614            Zhaire Smith        0
162           Deyonta Davis        0
663           Moritz Wagner        0
223          Melvin Frazier        0
514           Jahlil Okafor        0
542             Otto Porter        0
661          Nikola Vucevic        1
142           Bonzie Colson        0
344         Stanley Johnson        0
189            Jared Dudley        0
55            Dāvis Bertāns        0
247             Eric Gordon        0
408             Brook Lopez        0
220             Bryn Forbes        0
113         DeMarre Carroll        0
469        Donovan Mitchell        0
115            Vince Carter        0
675       Russell Westbrook        1
626          Caleb Swanigan        0
101           Deonte Burton        0
667               John Wall        0

[95 rows x 2 columns]

In [244]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

In [245]:
X_train

array([[-0.1701969 , -0.11745783, -0.21110926, ...,  2.45872039,
         0.28788854, -0.13720807],
       [ 0.25933563,  0.53002847, -0.51584534, ...,  0.14294886,
        -0.2365542 ,  0.13885128],
       [-0.88608444, -0.99618925,  0.80006048, ..., -0.88628293,
        -0.2365542 , -0.8963713 ],
       ...,
       [ 1.97746573,  1.82500108,  0.57843424, ..., -0.11435909,
         0.28788854,  1.88147597],
       [ 0.45023897,  0.76127358, -0.5712519 , ...,  1.68679654,
        -0.76099695,  0.62195516],
       [ 1.21385235,  1.31626184,  0.06592355, ...,  1.17218065,
         0.81233129,  1.13956645]])

In [246]:
from sklearn.linear_model import LogisticRegression

classifier = LogisticRegression()



In [252]:
classifier.fit(X_train, Y_train.drop('Player', axis = 1).values)


/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [253]:
y_pred = classifier.predict(X_test)

In [254]:
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0])

In [257]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test.drop('Player', axis =1).values, y_pred)

In [258]:
cm

array([[87,  0],
       [ 3,  5]])

In [259]:
temp = classifier.predict_proba(X_test)

In [113]:
def truncate(n, decimals=0):
    multiplier = 10 ** decimals
    return int(n * multiplier) / multiplier

In [270]:
Y_test.values[3][0]

'Daniel Theis'

In [273]:
a = []
for index in range(len(temp)):
    t = []
    for elem in temp[index]:
        t += [truncate(elem,2)]
    t += [Y_test.values[index][0]]
    a+=[t]
a

[[0.92, 0.07, 'Kevin Love'],
 [0.99, 0.0, 'Cristiano Felício'],
 [0.99, 0.0, 'Mario Hezonja'],
 [0.99, 0.0, 'Daniel Theis'],
 [0.98, 0.01, 'P.J. Tucker'],
 [0.99, 0.0, 'Tyler Cavanaugh'],
 [0.99, 0.0, 'Tyler Dorsey'],
 [0.99, 0.0, 'Deng Adel'],
 [0.99, 0.0, 'Omari Spellman'],
 [0.99, 0.0, 'T.J. Leaf'],
 [0.99, 0.0, 'George Hill'],
 [0.99, 0.0, 'Gorgui Dieng'],
 [0.99, 0.0, 'Quinn Cook'],
 [0.95, 0.04, 'Robert Covington'],
 [0.99, 0.0, 'Jaylen Morris'],
 [0.99, 0.0, 'Tyler Zeller'],
 [0.97, 0.02, 'Cedi Osman'],
 [0.84, 0.15, 'Khris Middleton'],
 [0.94, 0.05, 'Justise Winslow'],
 [0.99, 0.0, 'Mike Muscala'],
 [0.99, 0.0, 'Malcolm Miller'],
 [0.99, 0.0, 'Udonis Haslem'],
 [0.99, 0.0, 'DeVaughn Akoon-Purcell'],
 [0.99, 0.0, 'Ray Spalding'],
 [0.98, 0.01, 'Noah Vonleh'],
 [0.95, 0.04, 'Steven Adams'],
 [0.99, 0.0, 'Josh Okogie'],
 [0.99, 0.0, 'Keita Bates-Diop'],
 [0.99, 0.0, 'Demetrius Jackson'],
 [0.54, 0.45, 'Kemba Walker'],
 [0.87, 0.12, 'Al Horford'],
 [0.95, 0.04, 'Dennis Smith Jr.'],

In [359]:
from sklearn.ensemble import RandomForestClassifier
classifier2 = RandomForestClassifier(n_estimators=37)

In [424]:
dataset = pd.read_csv('./data/players.csv')

all_traded_players = set()
for row in dataset.index:
    #print(dataset["Tm"][row])
    if dataset["Tm"][row] == "TOT":
        all_traded_players.add(dataset['Player'][row])
        
#print(all_traded_players)

for index,row in dataset.iterrows():
    if row['Player'] in all_traded_players and row['Tm'] != 'TOT':
        #print("hello")
        dataset.drop(index, inplace=True)
    if row["Player"] == "Dwyane Wade":
        dataset.drop(index, inplace=True)
    if row["Player"] == "Dirk Nowitzki":
        dataset.drop(index, inplace=True)

In [425]:
dataset = dataset.drop('Id', axis=1)
dataset = dataset.drop('Unnamed: 0', axis=1)
dataset = dataset.drop('Pos', axis=1)
dataset = dataset.drop('Tm', axis=1)
dataset = dataset.drop('first', axis=1)
dataset = dataset.drop('last', axis=1)
#dataset = dataset.drop('Player', axis=1)

dataset = dataset.dropna()

X = dataset.drop('Player',axis = 1).iloc[:,:-1]
Y = dataset[["Player", "allstar"]]

X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size = 0.2, random_state=24)

In [446]:
#Y = dataset[['Player', 'allstar']]
X

Age   G  GS    MP    FG   FGA    FG%   3P  3PA    3P%  ...     FT%  ORB  \
0     25  31   2  19.0   1.8   5.1  0.357  1.3  4.1  0.323  ...   0.923  0.2   
1     28  10   0  12.3   0.4   1.8  0.222  0.2  1.5  0.133  ...   0.700  0.3   
2     22  34   1  12.6   1.1   3.2  0.345  0.7  2.2  0.338  ...   0.778  0.3   
3     25  80  80  33.4   6.0  10.1  0.595  0.0  0.0  0.000  ...   0.500  4.9   
4     21  82  28  23.3   3.4   5.9  0.576  0.0  0.2  0.200  ...   0.735  2.0   
5     21  19   3  10.2   0.6   1.9  0.306  0.3  1.2  0.261  ...   1.000  0.2   
6     25   7   0   3.1   0.4   1.4  0.300  0.0  0.6  0.000  ...   0.500  0.1   
7     33  81  81  33.2   8.4  16.3  0.519  0.1  0.5  0.238  ...   0.847  3.1   
8     21  10   1  12.0   1.3   3.9  0.333  0.3  1.2  0.250  ...   0.667  1.1   
9     23  38   2  10.9   1.8   4.7  0.376  0.8  2.6  0.323  ...   0.750  0.1   
10    20  80  80  26.2   4.2   7.1  0.590  0.1  0.6  0.133  ...   0.709  2.4   
11    26  19   1  21.9   3.4   7.4  0.461  0.9  1.9  0.472  ...   0.778  0.4   
12    28  81  81  28.3   3.2   7.3  0.433  1.2  3.5  0.343  ...   0.867  1.4   
13    25  48   4   9.6   1.3   3.3  0.408  0.5  1.6  0.312  ...   0.743  0.5   
14    25  43  40  29.8   3.5   6.4  0.543  0.2  0.8  0.265  ...   0.578  1.1   
15    30  25   8  12.9   0.8   2.8  0.304  0.4  1.6  0.225  ...   0.750  0.7   
19    24  72  72  32.8  10.0  17.3  0.578  0.7  2.8  0.256  ...   0.729  2.2   
21    34  10   2  29.4   4.9  12.1  0.405  2.1  6.4  0.328  ...   0.682  0.9   
22    21  67   6  20.2   2.7   6.0  0.453  1.0  3.0  0.332  ...   0.581  0.9   
23    24  81  32  24.2   2.3   5.2  0.447  1.0  2.7  0.373  ...   0.873  0.3   
24    33  69  69  34.0   4.3  10.7  0.399  2.1  6.3  0.334  ...   0.793  0.7   
27    31  81  81  28.0   3.9   8.4  0.470  1.6  3.8  0.421  ...   0.866  0.5   
28    20  71  70  30.7   7.2  12.3  0.585  0.0  0.1  0.000  ...   0.746  3.1   
29    23  43  13  17.7   2.8   6.0  0.475  0.9  2.0  0.437  ...   0.739  0.2   
30    19  62   4  25.3   5.7  11.4  0.504  0.5  1.5  0.313  ...   0.691  2.6   
31    25  15   0  10.1   0.3   1.3  0.200  0.1  0.9  0.077  ...   0.833  0.1   
34    22  16   0   5.9   0.6   2.1  0.303  0.1  0.6  0.222  ...   0.727  0.1   
35    21  47  45  30.3   3.9   9.7  0.406  1.6  4.9  0.329  ...   0.417  1.1   
36    20  47   1  16.3   2.5   5.2  0.481  0.4  1.5  0.300  ...   0.587  1.4   
37    34  38   0  19.8   4.2  10.1  0.418  1.0  3.4  0.297  ...   0.705  0.3   
..   ...  ..  ..   ...   ...   ...    ...  ...  ...    ...  ...     ...  ...   
665   28  82  82  34.9   8.9  20.5  0.434  3.2  8.9  0.356  ...   0.844  0.6   
666   20  17   0   6.9   0.9   2.7  0.348  0.3  0.8  0.385  ...   0.800  0.0   
667   28  32  32  34.5   7.7  17.3  0.444  1.6  5.3  0.302  ...   0.697  0.5   
668   24  62   0  10.1   1.5   3.5  0.424  0.1  0.3  0.211  ...   0.526  0.3   
669   24  55  47  28.2   4.8  10.8  0.441  2.2  5.7  0.390  ...   0.819  0.4   
670   29  36   0   9.5   1.4   2.9  0.476  0.4  1.1  0.410  ...   0.857  0.1   
671   25  43  36  31.6   6.9  14.2  0.486  1.8  4.2  0.428  ...   0.815  0.7   
672   27  18   3  14.1   0.9   2.7  0.333  0.3  1.3  0.208  ...   0.750  0.4   
673   24  15   0  11.6   1.0   3.4  0.294  0.1  1.1  0.125  ...   0.700  0.3   
674   22  11   0   3.3   0.6   1.2  0.538  0.3  0.6  0.429  ...   0.500  0.0   
675   30  73  73  36.0   8.6  20.2  0.428  1.6  5.6  0.290  ...   0.656  1.5   
676   24  67  55  25.8   3.9   8.1  0.479  0.7  2.1  0.338  ...   0.772  0.5   
678   29  72  53  23.3   5.4   9.4  0.571  0.0  0.2  0.125  ...   0.449  3.6   
679   23  73  73  34.8   6.8  16.6  0.412  1.6  4.8  0.339  ...   0.699  1.1   
680   26   5   0   5.2   1.6   2.6  0.615  0.0  0.2  0.000  ...   0.500  0.8   
681   28  15   0   8.5   1.1   2.3  0.486  0.3  1.1  0.313  ...   0.000  0.1   
682   23  24   0  15.5   2.7   4.6  0.591  0.0  0.1  0.000  ...   0.563  2.0   
683   24  46  29  23.5   2.3   6.1  0.384  1.1  3.4  0.333  ...   0.684  1.2   
684  

In [426]:
classifier2.fit(X_train,Y_train.drop('Player',axis=1).values)

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """Entry point for launching an IPython kernel.


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=37, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [427]:
Y_pred = classifier2.predict(X_test)
Y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 0])

In [429]:
cm = confusion_matrix(Y_test.drop('Player',axis=1).values, Y_pred)
cm

array([[86,  1],
       [ 1,  7]])

In [431]:
results = []
temp = classifier2.predict_proba(X_test)

a = []
for index in range(len(temp)):
    t = []
    for elem in temp[index]:
        t += [truncate(elem,3)]
    t += [Y_test.values[index][0],Y_test.values[index][1]]
    results+=[t]
    
#for index in range(len()):

In [432]:
results

[[0.945, 0.054, 'Kevin Love', 0],
 [1.0, 0.0, 'Cristiano Felício', 0],
 [1.0, 0.0, 'Mario Hezonja', 0],
 [1.0, 0.0, 'Daniel Theis', 0],
 [0.945, 0.054, 'P.J. Tucker', 0],
 [1.0, 0.0, 'Tyler Cavanaugh', 0],
 [1.0, 0.0, 'Tyler Dorsey', 0],
 [1.0, 0.0, 'Deng Adel', 0],
 [1.0, 0.0, 'Omari Spellman', 0],
 [1.0, 0.0, 'T.J. Leaf', 0],
 [1.0, 0.0, 'George Hill', 0],
 [1.0, 0.0, 'Gorgui Dieng', 0],
 [1.0, 0.0, 'Quinn Cook', 0],
 [0.864, 0.135, 'Robert Covington', 0],
 [1.0, 0.0, 'Jaylen Morris', 0],
 [1.0, 0.0, 'Tyler Zeller', 0],
 [1.0, 0.0, 'Cedi Osman', 0],
 [0.972, 0.027, 'Khris Middleton', 1],
 [1.0, 0.0, 'Justise Winslow', 0],
 [1.0, 0.0, 'Mike Muscala', 0],
 [1.0, 0.0, 'Malcolm Miller', 0],
 [1.0, 0.0, 'Udonis Haslem', 0],
 [1.0, 0.0, 'DeVaughn Akoon-Purcell', 0],
 [1.0, 0.0, 'Ray Spalding', 0],
 [1.0, 0.0, 'Noah Vonleh', 0],
 [0.918, 0.081, 'Steven Adams', 0],
 [1.0, 0.0, 'Josh Okogie', 0],
 [1.0, 0.0, 'Keita Bates-Diop', 0],
 [1.0, 0.0, 'Demetrius Jackson', 0],
 [0.135, 0.864, 'Kemba W

In [430]:
Y_test

Player  allstar
410              Kevin Love        0
215       Cristiano Felício        0
288           Mario Hezonja        0
639            Daniel Theis        0
650             P.J. Tucker        0
124         Tyler Cavanaugh        0
182            Tyler Dorsey        0
5                 Deng Adel        0
619          Omari Spellman        0
390               T.J. Leaf        0
293             George Hill        0
178            Gorgui Dieng        0
145              Quinn Cook        0
147        Robert Covington        0
480           Jaylen Morris        0
701            Tyler Zeller        0
519              Cedi Osman        0
457         Khris Middleton        1
689         Justise Winslow        0
491            Mike Muscala        0
462          Malcolm Miller        0
283           Udonis Haslem        0
6    DeVaughn Akoon-Purcell        0
616            Ray Spalding        0
660             Noah Vonleh        0
3              Steven Adams        0
516             Josh Okogie        0
42         Keita Bates-Diop        0
324       Demetrius Jackson        0
665            Kemba Walker        1
..                      ...      ...
671             T.J. Warren        0
445             CJ McCollum        0
227         Jimmer Fredette        0
86            Lorenzo Brown        0
317          Ersan İlyasova        0
368            Luke Kennard        0
205             Jacob Evans        0
512            Kyle O'Quinn        0
453             Jodie Meeks        0
614            Zhaire Smith        0
162           Deyonta Davis        0
663           Moritz Wagner        0
223          Melvin Frazier        0
514           Jahlil Okafor        0
542             Otto Porter        0
661          Nikola Vucevic        1
142           Bonzie Colson        0
344         Stanley Johnson        0
189            Jared Dudley        0
55            Dāvis Bertāns        0
247             Eric Gordon        0
408             Brook Lopez        0
220             Bryn Forbes        0
113         DeMarre Carroll        0
469        Donovan Mitchell        0
115            Vince Carter        0
675       Russell Westbrook        1
626          Caleb Swanigan        0
101           Deonte Burton        0
667               John Wall        0

[95 rows x 2 columns]

In [396]:
classifier2.predict_proba(X_test)

array([[0.94594595, 0.05405405],
       [1.        , 0.        ],
       [1.        , 0.        ],
       [1.        , 0.        ],
       [0.89189189, 0.10810811],
       [1.        , 0.        ],
       [1.        , 0.        ],
       [1.        , 0.        ],
       [1.        , 0.        ],
       [1.        , 0.        ],
       [1.        , 0.        ],
       [1.        , 0.        ],
       [1.        , 0.        ],
       [0.89189189, 0.10810811],
       [1.        , 0.        ],
       [1.        , 0.        ],
       [1.        , 0.        ],
       [0.97297297, 0.02702703],
       [1.        , 0.        ],
       [1.        , 0.        ],
       [1.        , 0.        ],
       [1.        , 0.        ],
       [1.        , 0.        ],
       [1.        , 0.        ],
       [1.        , 0.        ],
       [0.91891892, 0.08108108],
       [1.        , 0.        ],
       [1.        , 0.        ],
       [1.        , 0.        ],
       [0.13513514, 0.86486486],
       [1.

In [376]:
importances = classifier2.feature_importances_
importances

temp = []
dataset.columns

for index in range(len(importances)):
    temp += [(importances[index], dataset.columns[index])]

temp.sort(key = lambda x : x[0], reverse=True)
temp

[(0.17330136244395714, 'FGA'),
 (0.16987699011141702, 'PTS'),
 (0.12303619586554672, 'FG'),
 (0.0838969849014597, '2PA'),
 (0.0675473852636892, 'FT'),
 (0.04414169128944757, 'TRB'),
 (0.040727947872894375, '2P'),
 (0.039325781315700734, 'DRB'),
 (0.035168661915634176, 'TOV'),
 (0.035014995474651325, 'MP'),
 (0.034886566776028395, '3P'),
 (0.03220597244411648, '3PA'),
 (0.03057297544783266, 'GS'),
 (0.023298012278616657, 'STL'),
 (0.017022823755839512, 'AST'),
 (0.014900976679117746, 'FTA'),
 (0.012264823755067027, 'eFG%'),
 (0.007409941593479821, 'FT%'),
 (0.006592395414162001, 'Age'),
 (0.005295639099181873, '3P%'),
 (0.003511876302159861, 'BLK')]

In [377]:
np.sort(importances)

array([0.00351188, 0.00529564, 0.0065924 , 0.00740994, 0.01226482,
       0.01490098, 0.01702282, 0.02329801, 0.03057298, 0.03220597,
       0.03488657, 0.035015  , 0.03516866, 0.03932578, 0.04072795,
       0.04414169, 0.06754739, 0.08389698, 0.1230362 , 0.16987699,
       0.17330136])

In [433]:
import pickle

In [434]:
saved_model = pickle.dumps(classifier2)

In [435]:
from sklearn.externals import joblib
joblib.dump(classifier2, 'allstar_model.pkl')

['allstar_model.pkl']

In [436]:
temp = joblib.load('allstar_model.pkl')

In [437]:
temp.predict(X_test)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 0])

In [440]:
t_x = X_test.values[0]

In [441]:
t_x

array([30.   , 22.   , 21.   , 27.2  ,  5.   , 12.9  ,  0.385,  2.4  ,
        6.7  ,  0.361,  2.5  ,  6.2  ,  0.412,  0.479,  4.7  ,  5.2  ,
        0.904,  1.5  ,  9.4  , 10.9  ,  2.2  ,  0.3  ,  0.2  ,  1.9  ,
        2.5  , 17.   ])

In [445]:
temp.predict_proba([t_x])

array([[0.94594595, 0.05405405]])

In [448]:
np.array(np.array([1,3,2]))

array([1, 3, 2])

In [450]:
X.columns

Index(['Age', 'G', 'GS', 'MP', 'FG', 'FGA', 'FG%', '3P', '3PA', '3P%', '2P',
       '2PA', '2P%', 'eFG%', 'FT', 'FTA', 'FT%', 'ORB', 'DRB', 'TRB', 'AST',
       'STL', 'BLK', 'TOV', 'PF', 'PTS'],
      dtype='object')